name: Auto Label Issues

on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar labels com base no título
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = context.payload.issue.title.toLowerCase();
            let labels = [];

            if (issueTitle.includes("bug")) {
              labels.push("bug");
            }
            if (issueTitle.includes("documentação")) {
              labels.push("documentação");
            }

            if (labels.length > 0) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              });
            }
