name: Unit tests
on:
  push:
    branches:
      - develop
      - documentation/tests
  pull_request:
    branches: ["develop"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Config environment
      run: sudo apt-get update && sudo apt-get install -y build-essential check

    - name: Make test files
      run: cd test && make
      
    - name: Run test files
      run: cd /test/bin && ./test_vmu && ./test_ev && ./test_iec
