name: Unit tests

on:
  push:
    branches:
      - develop
      - documentation/tests
  pull_request:
    branches: ["develop"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential check git perl

    - name: Install latest lcov
      run: |
        git clone https://github.com/linux-test-project/lcov.git
        cd lcov
        sudo make install

    - name: Build and test
      run: |
        make clean
        make
        make test
        make coverage
