name: Unit tests

on:
  push:
    branches:
      - develop
      - documentation/tests
  pull_request:
    branches: ["develop"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential wget libgmp-dev libmpfr-dev libmpc-dev libisl-dev check git perl

    - name: Install GCC 14.2.0
      run: |
        wget https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.gz
        tar -xzf gcc-14.2.0.tar.gz
        cd gcc-14.2.0
        ./contrib/download_prerequisites
        mkdir build && cd build
        ../configure --disable-multilib --enable-languages=c,c++ --prefix=$HOME/gcc-14.2.0
        make -j$(nproc)
        make install
        echo "$HOME/gcc-14.2.0/bin" >> $GITHUB_PATH

    - name: Install latest lcov
      run: |
        git clone https://github.com/linux-test-project/lcov.git
        cd lcov
        sudo make install

    - name: Build and test
      run: |
        make clean
        make
        make test
        make coverage
