name: Unit tests

on:
  push:
    branches:
      - develop
      - documentation/tests
  pull_request:
    branches: ["develop"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential wget libgmp-dev libmpfr-dev libmpc-dev libisl-dev check git perl

    - name: Install GCC 14.2.0 and CAN tools
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install -y gcc-14 \
          linux-modules-extra-$(uname -r) \
          libcunit1 libcunit1-doc libcunit1-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
        gcc --version
        gcov --version

    - name: Install LCOV 2.3-1
      run: |
        sudo apt install -y cpanminus  # instala cpanm
        curl -LO https://github.com/linux-test-project/lcov/releases/download/v2.3/lcov-2.3.tar.gz
        tar -xzf lcov-2.3.tar.gz
        cd lcov-2.3
        sudo make install
        sudo cpanm Capture::Tiny
        sudo cpanm DateTime
        lcov --version

    - name: Build and test
      run: |
        make clean
        make
        make test
        make coverage
